trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: 'src/todo.sln'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'src/todo.sln'
      arguments: '--configuration Release --no-restore'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'src/todo.sln'
      arguments: '--no-restore --verbosity normal'
